# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build:
        filters:
          branches:
            only: /(ima|evm)-.*/
jobs:
  build:
    docker:
      - image: buildpack-deps:focal
    resource_class: medium
    steps:
      - run:
          name: fetch artifacts
          command: |
            curl -H "Circle-Token: e7c877a2700a954bcbfe33aa22e83e731e0e714e" https://circleci.com/api/v1.1/project/github/robertosassu/linux/latest/artifacts | grep -o 'https://[^"]*' | wget --verbose --header "Circle-Token: e7c877a2700a954bcbfe33aa22e83e731e0e714e" --input-file -
      - run: apt-get update
      - run: apt-get --yes --force-yes install build-essential make autoconf automake libtool libssl-dev libkeyutils-dev attr xxd
      - checkout
      - run: sh build.sh
